version: '3'
services:
  mysql:
    container_name: prestashop-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    ports:
      - 3306:3306
    networks:
      - prestashop_network
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    environment:
      DB_SERVER: mysql
    ports:
      - 80:80
    networks:
      - prestashop_network
networks:
    prestashop_network:
